name: Trivy Docker Scan

on:
  push:
    branches: [ "main" ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t tp-devsecops:latest .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tp-devsecops:latest
          format: table
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
